### PR TITLE
Add table block implementation

### LINKED ISSUE #47: [DNA page] [mobile] Enhanced cards block

### PR DESCRIPTION
**Pull request by ujjwal5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #47 

Test URLs:
- Before: https://main--com--ancestry.aem.live/drafts/ujjgupta/table-new
- After: https://47-implement-table-block--com--ancestry.aem.live/drafts/ujjgupta/table-new

### CODE REVIEW

**Comment by FentPams** [comment]
@ujjwal5 Great work! Just few tweaks on styling:
1. Element will float out of its position when some` <p>` begin to take more space. Could probably solve this by adding some `min-height` ?
Screenshot 2024-10-31 at 8 45 41 AM

2. In the smaller size (<400 px)  `<th> ` element will overflow
Screenshot 2024-10-31 at 8 30 55 AM

3. Could decrease the` <tr>` 's gap when in smaller screen, and center the markers.
Screenshot 2024-10-31 at 8 50 04 AM

4. The link issue for two buttons :` Return to top `and `See offer details`, for some reasons, the links are given full url to google drive, while we only need to keep the part starts from `#` (I fixed the return to top link)
- For the **See offer details** button, we will jump to the **Offer Details** part, in this case, the Offer details should be heading (h1,h2, or h3....) to enable it has an id, then we attach the id (e.g. #offer-detail) to the button.

Screenshot 2024-10-31 at 9 05 06 AM

Screenshot 2024-10-31 at 9 05 22 AM

**Comment by ujjwal5** [comment]
> @ujjwal5 Great work! Just few tweaks on styling:
> 
> 1. Element will float out of its position when some` <p>` begin to take more space. Could probably solve this by adding some `min-height` ?
> 
> Screenshot 2024-10-31 at 8 45 41 AM
> 2. In the smaller size (<400 px)  `<th> ` element will overflow
> 
> Screenshot 2024-10-31 at 8 30 55 AM
> 3. Could decrease the` <tr>` 's gap when in smaller screen, and center the markers.
> 
> Screenshot 2024-10-31 at 8 50 04 AM
> 4. The link issue for two buttons :`Return to top`and `See offer details`, for some reasons, the links are given full url to google drive, while we only need to keep the part starts from `#` (I fixed the return to top link)
> 
> * For the **See offer details** button, we will jump to the **Offer Details** part, in this case, the Offer details should be heading (h1,h2, or h3....) to enable it has an id, then we attach the id (e.g. #offer-detail) to the button. And, the offer details probably need re-styling
> 
> Screenshot 2024-10-31 at 9 05 06 AM Screenshot 2024-10-31 at 9 05 22 AM

Thanks for looking at the PR, I've fixed above issues as mentioned. One tricky thing to handle #2, I have used overflow-x as auto, to have scroll only to the table. Let me know if you have a better alternative.

**Comment by FentPams** [comment]
@ujjwal5  I think there are two ways probably could try: 
1. comment out the `display:block` and `display:flex`, using  `display:table` instead to prevent overflow, and adjust the responsive style in smaller screen
`.section.table-container` .table.product-compare table {
  display: table;
  width: 100%;
  table-layout: fixed;
  border-collapse: collapse;
  overflow: hidden;
}

.section.table-container .table.product-compare table th,
.section.table-container .table.product-compare table td {
  display: table-cell;
  vertical-align: top;
}
`
2. Simply keep your` overflow-x:auto` and adjust the responsive style in smaller screen e.g. shrink the text size, gap, to make it "looks good" in the smallest screen we mostly can touch ( iphone SE ), but it do have the bar thing come out when screen keep shrinking..

**Review by FentPams — APPROVED** [review]

**Comment by ujjwal5** [comment]
> @ujjwal5 I think there are two ways probably could try:
> 
> 1. comment out the `display:block` and `display:flex`, using  `display:table` instead to prevent overflow, and adjust the responsive style in smaller screen (e.g. decrease text img size, decrease gap...)
> 
> ```
>   .section.table-container .table.product-compare table {
>     display: table;
>   }
>   
>   .section.table-container .table.product-compare table th,
>   .section.table-container .table.product-compare table td {
>     display: table-cell;
>   }
> ```
> 
> 2. Simply keep your` overflow-x:auto` and adjust the responsive style in smaller screen e.g. shrink the text size, gap, to make it "looks good" in the smallest screen we mostly can touch ( iphone SE ), but it do have the bar thing come out when screen keep shrinking..

Added a media breakpoint for <410px.

**Pull request merged**
